"""
api.py
--------
Simple REST API exposing the OEE Manufacturing Dashboard data.

Complements Grafana: while Grafana is for human visualization, this API
lets other systems (a web app, another service, an automation script)
consume the same data programmatically.

Connects to the same Neon database used by Grafana.

How to run locally:
    pip install fastapi uvicorn sqlalchemy psycopg2-binary python-dotenv
    uvicorn api:app --reload

Then open in your browser:
    http://127.0.0.1:8000/docs
    (interactive documentation auto-generated by FastAPI)
"""

import os
from datetime import date
from typing import Optional, List

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()  # loads variables from a .env file if present

app = FastAPI(
    title="OEE Manufacturing API",
    description="API to query OEE, Takt Time, and JPH metrics for a simulated plant.",
    version="1.0.0",
)


# =========================================================
# Response models (Pydantic)
# Defining these explicitly makes the /docs documentation show
# each field, its type, and its description — without this,
# Swagger only sees a generic dictionary.
# =========================================================

class OEEGeneral(BaseModel):
    oee: float = Field(..., description="Overall OEE as a percentage (0-100)")
    disponibilidad: float = Field(..., description="Availability as a percentage")
    rendimiento: float = Field(..., description="Performance as a percentage")
    calidad: float = Field(..., description="Quality as a percentage")


class OEEPorMaquina(BaseModel):
    maquina: str = Field(..., description="Machine name")
    linea: str = Field(..., description="Line the machine belongs to")
    oee_promedio: float = Field(..., description="Average OEE of the machine, as a percentage")


class CausaParada(BaseModel):
    causa: str = Field(..., description="Downtime cause name")
    categoria: str = Field(..., description="'Planned' or 'Unplanned'")
    minutos_totales: float = Field(..., description="Total minutes lost to this cause")
    num_eventos: int = Field(..., description="Number of times this cause occurred")


class CuelloDeBotella(BaseModel):
    maquina: str = Field(..., description="Machine name")
    linea: str = Field(..., description="Line the machine belongs to")
    pct_cumplimiento_takt: float = Field(
        ..., description="% of days the machine met its Takt Time target (below 100 = bottleneck)"
    )


class TendenciaDiaria(BaseModel):
    fecha: str = Field(..., description="Date in YYYY-MM-DD format")
    oee: float = Field(..., description="Average OEE for that day, as a percentage")
    disponibilidad: float = Field(..., description="Average Availability for that day")
    rendimiento: float = Field(..., description="Average Performance for that day")
    calidad: float = Field(..., description="Average Quality for that day")


def get_engine():
    """
    Creates the database connection, reading the connection string
    from an environment variable (never hardcoded in the code,
    for security — especially since this code is on GitHub).
    """
    connection_string = os.getenv("NEON_CONNECTION_STRING")
    if not connection_string:
        raise RuntimeError(
            "Missing NEON_CONNECTION_STRING environment variable. "
            "Create a .env file with that variable (see .env.example)."
        )
    if connection_string.startswith("postgresql://"):
        connection_string = connection_string.replace(
            "postgresql://", "postgresql+psycopg2://", 1
        )
    return create_engine(connection_string)


engine = None  # initialized on first request (lazy loading)


def get_conn():
    global engine
    if engine is None:
        engine = get_engine()
    return engine.connect()


@app.get("/")
def raiz():
    """Root endpoint — confirms the API is alive."""
    return {
        "message": "OEE Manufacturing API is running.",
        "documentation": "/docs",
    }


@app.get("/oee/general", response_model=OEEGeneral)
def oee_general(
    linea: Optional[str] = Query(None, description="Filter by line name"),
    maquina: Optional[str] = Query(None, description="Filter by machine name"),
):
    """Returns overall OEE and its 3 factors, averaged across the full history."""
    sql = """
        SELECT
            AVG(o.oee) * 100 AS oee,
            AVG(o.disponibilidad) * 100 AS disponibilidad,
            AVG(o.rendimiento) * 100 AS rendimiento,
            AVG(o.calidad) * 100 AS calidad
        FROM oee_turno o
        JOIN maquinas m ON o.id_maquina = m.id_maquina
        JOIN lineas l ON o.id_linea = l.id_linea
        WHERE (:linea IS NULL OR l.nombre = :linea)
          AND (:maquina IS NULL OR m.nombre = :maquina)
    """
    with get_conn() as conn:
        row = conn.execute(text(sql), {"linea": linea, "maquina": maquina}).mappings().first()
    if row is None or row["oee"] is None:
        raise HTTPException(status_code=404, detail="No data found for that filter.")
    return {k: round(v, 2) for k, v in row.items()}


@app.get("/oee/por-maquina", response_model=List[OEEPorMaquina])
def oee_por_maquina():
    """Returns average OEE per machine, ordered lowest to highest."""
    sql = """
        SELECT
            m.nombre AS maquina,
            l.nombre AS linea,
            AVG(o.oee) * 100 AS oee_promedio
        FROM oee_turno o
        JOIN maquinas m ON o.id_maquina = m.id_maquina
        JOIN lineas l ON o.id_linea = l.id_linea
        GROUP BY m.nombre, l.nombre
        ORDER BY oee_promedio ASC
    """
    with get_conn() as conn:
        rows = conn.execute(text(sql)).mappings().all()
    return [
        {"maquina": r["maquina"], "linea": r["linea"], "oee_promedio": round(r["oee_promedio"], 2)}
        for r in rows
    ]


@app.get("/paradas/pareto", response_model=List[CausaParada])
def pareto_causas(limite: int = Query(10, ge=1, le=50, description="Maximum number of causes to return")):
    """Returns downtime causes ranked by total accumulated minutes (Pareto)."""
    sql = """
        SELECT
            c.nombre AS causa,
            c.categoria,
            SUM(p.duracion_min) AS minutos_totales,
            COUNT(*) AS num_eventos
        FROM paradas p
        JOIN causas_parada c ON p.id_causa = c.id_causa
        GROUP BY c.nombre, c.categoria
        ORDER BY minutos_totales DESC
        LIMIT :limite
    """
    with get_conn() as conn:
        rows = conn.execute(text(sql), {"limite": limite}).mappings().all()
    return [
        {
            "causa": r["causa"],
            "categoria": r["categoria"],
            "minutos_totales": round(r["minutos_totales"], 1),
            "num_eventos": r["num_eventos"],
        }
        for r in rows
    ]


@app.get("/takt-jph/cuellos-de-botella", response_model=List[CuelloDeBotella])
def cuellos_de_botella():
    """
    Returns machines that do NOT meet their Takt Time 100% of the time,
    ordered from worst to best compliance — identifies bottlenecks.
    """
    sql = """
        SELECT
            m.nombre AS maquina,
            l.nombre AS linea,
            AVG(CASE WHEN t.cumple_takt THEN 100.0 ELSE 0 END) AS pct_cumplimiento
        FROM takt_jph t
        JOIN maquinas m ON t.id_maquina = m.id_maquina
        JOIN lineas l ON t.id_linea = l.id_linea
        GROUP BY m.nombre, l.nombre
        HAVING AVG(CASE WHEN t.cumple_takt THEN 100.0 ELSE 0 END) < 100
        ORDER BY pct_cumplimiento ASC
    """
    with get_conn() as conn:
        rows = conn.execute(text(sql)).mappings().all()
    return [
        {
            "maquina": r["maquina"],
            "linea": r["linea"],
            "pct_cumplimiento_takt": round(r["pct_cumplimiento"], 1),
        }
        for r in rows
    ]


@app.get("/oee/tendencia", response_model=List[TendenciaDiaria])
def oee_tendencia(
    fecha_inicio: Optional[date] = Query(None, description="Format: YYYY-MM-DD"),
    fecha_fin: Optional[date] = Query(None, description="Format: YYYY-MM-DD"),
):
    """Returns the daily OEE trend and its 3 factors over a date range."""
    sql = """
        SELECT
            fecha,
            AVG(oee) * 100 AS oee,
            AVG(disponibilidad) * 100 AS disponibilidad,
            AVG(rendimiento) * 100 AS rendimiento,
            AVG(calidad) * 100 AS calidad
        FROM oee_turno
        WHERE (:fecha_inicio IS NULL OR fecha >= :fecha_inicio)
          AND (:fecha_fin IS NULL OR fecha <= :fecha_fin)
        GROUP BY fecha
        ORDER BY fecha
    """
    with get_conn() as conn:
        rows = conn.execute(
            text(sql), {"fecha_inicio": fecha_inicio, "fecha_fin": fecha_fin}
        ).mappings().all()
    return [
        {
            "fecha": str(r["fecha"]),
            "oee": round(r["oee"], 2),
            "disponibilidad": round(r["disponibilidad"], 2),
            "rendimiento": round(r["rendimiento"], 2),
            "calidad": round(r["calidad"], 2),
        }
        for r in rows
    ]
